In [102]:
import pandas as pd
import numpy as np 
import requests

In [103]:
url = "http://localhost:3000/api/graphql"
headers={"Content-Type": "application/json"}
body = {
    "query": """
    query Users {
      users {
        _id
        interactions {
          movieId
          rating
        }
      }
    }
    """
}

response = requests.post(url, json=body, headers=headers)
data=[]
try:
    data=response.json()['data']['users']
except ValueError:
    print("Error: Invalid JSON response. Status Code:", response.status_code)
    print("Response Text:", response.text)

In [104]:
#create a flattend list
flattened_data = []
for user in data:
    user_id=user['_id']
    for interaction in user['interactions']:
        flattened_data.append({
            'user_id':user_id,
            'movie_id':interaction['movieId'],
            'rating':interaction['rating']
        })
flattened_data
#convert into dataframe
data_frame=pd.DataFrame(flattened_data)
print(data_frame.columns)

Index(['user_id', 'movie_id', 'rating'], dtype='object')

In [105]:
#convert into user_movie matrix
user_movie_matrix = data_frame.pivot_table(index="user_id", columns="movie_id", values="rating",aggfunc='mean')
user_movie_matrix

movie_id,67b74ca00106f2047810825d,67b752290106f204781082d7,67b9de3b54720ab39e7545da,67cb271aa87f3b8f8f79726a,67cc43ca76bdb95f827c7782,67cc469b76bdb95f827c7b3f,67cc55be76bdb95f827c8113,67cf1f24ecd7c832508adc9c,67dd897329af0958f589563e,67e2f2a35f6cd300680a3708,67e8094541c70d18248a9ff6
user_id,,,,,,,,,,,
67b9d787ce46683627debdca,5.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
67cb02cf8c985a197d764adf,NaN,NaN,5.0,4.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0
67e954ca047ce560a5bd55e2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN
67e95507047ce560a5bd5657,NaN,2.0,5.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN

In [106]:
import numpy as np

def matrix_fact(users, movies, learning_rate, iterations, lamda, latent_factors, rating_matrix):
    # Initialize matrices
    user_matrix = np.random.rand(users, latent_factors)
    movie_matrix = np.random.rand(movies, latent_factors)
    mask = ~np.isnan(rating_matrix)
    
    # Perform matrix factorization using Gradient Descent
    for _ in range(iterations):
        for i in range(users):
            for j in range(movies):
                if mask[i, j]:
                    error = rating_matrix[i, j] - np.dot(user_matrix[i, :], movie_matrix[j, :].T)
                    user_matrix[i, :] += learning_rate * (error * movie_matrix[j, :] - lamda * user_matrix[i, :])
                    movie_matrix[j, :] += learning_rate * (error * user_matrix[i, :] - lamda * movie_matrix[j, :])
    
    # Predictions
    predicted_ratings = np.dot(user_matrix, movie_matrix.T)
    return np.round(predicted_ratings, 2)

# Example Setup

no_of_users = user_movie_matrix.shape[0]
no_of_movies = user_movie_matrix.shape[1]
learning_rate = 0.01
iterations = 1000
lamda = 0.02
latent_factors = 4
rating_matrix_np = user_movie_matrix.to_numpy()
predictions=matrix_fact(no_of_users, no_of_movies, learning_rate, iterations, lamda, latent_factors, rating_matrix_np)
# predictions
predictions

array([[4.98, 3.95, 4.02, 4.22, 3.72, 4.12, 3.87, 4.02, 4.96, 4.12, 5.5 ],
       [4.49, 3.09, 4.94, 3.98, 3.98, 3.98, 3.98, 3.98, 4.98, 3.02, 4.97],
       [2.22, 1.65, 1.04, 1.79, 1.56, 1.85, 1.76, 1.52, 2.02, 3.96, 2.27],
       [4.33, 2.02, 4.98, 3.74, 3.74, 3.66, 4.06, 3.58, 4.97, 4.96, 4.12]])

In [107]:
predictions_df=pd.DataFrame(predictions,index=user_movie_matrix.index,columns=user_movie_matrix.columns)
predictions_long = predictions_df.reset_index().melt(id_vars='user_id', var_name='movie_id', value_name='predicted_rating')
data_to_insert=predictions_long.to_dict(orient='records')
# data_to_insert

In [110]:
from pymongo import MongoClient
client=MongoClient("mongodb+srv://patraavishek900:truefeedback@cluster0.exlrw.mongodb.net/bookMyshow?retryWrites=true&w=majority&appName=Cluster0")
db = client['bookMyshow']
dbCollection=db['predictions']
dbCollection.insert_many(data_to_insert)
print("Predictions successfully stored in MongoDB!")